---
title: "KI Acoustics - Exploratory Plots"
author: "Sean Dimoff"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
#load in packages
library(stringr)
library(tidyr)
#read in data
s5.18 <- read.csv(file ="C:/Users/Sean Dimoff/Documents/GitHub/Sean_Acoustics/Raw_Data/SPL.ACI_2018_MP_5.csv", header=TRUE, stringsAsFactors=FALSE)
s8.18 <- read.csv(file ="C:/Users/Sean Dimoff/Documents/GitHub/Sean_Acoustics/Raw_Data/SPL.ACI_2018_MP_8.csv", header=TRUE, stringsAsFactors=FALSE)
s32.18 <- read.csv(file ="C:/Users/Sean Dimoff/Documents/GitHub/Sean_Acoustics/Raw_Data/SPL.ACI_2018_MP_32.csv", header=TRUE, stringsAsFactors=FALSE)
s35.18 <- read.csv(file ="C:/Users/Sean Dimoff/Documents/GitHub/Sean_Acoustics/Raw_Data/SPL.ACI_2018_MP_35.csv", header=TRUE, stringsAsFactors=FALSE)
s40.18 <- read.csv(file ="C:/Users/Sean Dimoff/Documents/GitHub/Sean_Acoustics/Raw_Data/SPL.ACI_2018_MP_40.csv", header=TRUE, stringsAsFactors=FALSE)

#adding new column to each dataframe for site
s5.18$Site <- "5"
s8.18$Site <- "8"
s32.18$Site <- "32"
s35.18$Site <- "35"
s40.18$Site <- "40"

#renaming first column for each dataframe to something easy to replicate
names(s5.18)[1]<- "T.stamp"
names(s8.18)[1]<- "T.stamp"
names(s32.18)[1]<- "T.stamp"
names(s35.18)[1]<- "T.stamp"
names(s40.18)[1]<- "T.stamp"

#combining all sites onto one dataframe
all.18 <- rbind(s5.18, s8.18, s32.18, s35.18, s40.18)

#seperating first column
T.5 <- c(s5.18$T.stamp)

T.5 %>% seperate(T.5, sep = 6)
#T.5 <- str_split_fixed(T.5, "18", 2)
#T.5 <- str_split(T.5, "18", simplify = TRUE)
```

## R Markdown


```{r cars}
summary(cars)
```

## Including Plots


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
